src/main/java/muzusi/domain/post/exception/PostErrorType.java
src/main/java/muzusi/domain/stock/exception/StockErrorType.java
src/main/java/muzusi/domain/user/exception/UserErrorType.java
src/main/java/muzusi/global/response/error/ErrorResponse.java
src/main/java/muzusi/global/response/error/type/BaseErrorType.java
src/main/java/muzusi/global/response/error/type/CommonErrorType.java

- 앞자리가 0으로 시작하는 에러 코드 반환 시 출력 오류로 인한 code 필드 타입 수정
- `ErrorType` 내 `int code` → `String code` 
- 에러 코드 타입 수정에 따른 `ErrorResponse` 내 정적 팩토리 메서드 `.of(...)` 수정
- [기타] `UserErrorType` 내 인증 관련 에러 코드 삭제

Fix: 에러 코드 응답 시 출력 오류로 인한 수정

---

src/main/java/muzusi/application/auth/dto/SignUpDto.java
src/main/java/muzusi/application/auth/service/AuthService.java
src/main/java/muzusi/application/auth/service/client/KakaoClient.java
src/main/java/muzusi/application/auth/service/client/NaverClient.java
src/main/java/muzusi/application/auth/service/client/OAuthClient.java
src/main/java/muzusi/domain/user/entity/User.java
src/main/java/muzusi/domain/user/exception/UserErrorType.java
src/main/java/muzusi/domain/user/service/UserService.java
src/main/java/muzusi/presentation/auth/api/AuthApi.java
src/main/java/muzusi/presentation/auth/controller/AuthController.java

- close #17 
- 최초 로그인 시, 사용자 추가정보 입력
- OAuth 연결 로직 및 사용자 조회 로직 분리
- 회원 정보 추가 로직 구현 (회원가입)
OAuth관련 클래스에서 사용자의 정보를 찾고 없으면 새로 등록하는 메서드를 진행했는데, 단순히 통신만을 위해서 OAuth와 사용자 정보 불러오는 로직을 분리하였습니다!
그 과정에서 `signUp`과 `registerNewUser`의 의미가 헷갈리지 않나 라는 생각이 드는데
의견이 있으시다면 알려주시면 감사하겠습니다!

Feature: 회원가입 구현

---

src/main/java/muzusi/infrastructure/config/MongoConfig.java

- MongoDB Replica Set 미적용에 따른 Transaction 관련 설정 코드 삭제
- `MongoConfig` 내 Transaction 설정 코드 삭제

Fix: Replica Set 미적용에 따른 Transaction 설정 코드 삭제

---

src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
src/main/java/muzusi/application/kis/service/KisOAuthService.java
src/main/java/muzusi/global/redis/RedisService.java
src/main/java/muzusi/infrastructure/kis/KisConstant.java
src/main/java/muzusi/infrastructure/kis/KisOAuthClient.java
src/main/java/muzusi/infrastructure/kis/KisUrlConstant.java
src/main/java/muzusi/infrastructure/properties/KisProperties.java
src/main/resources/application.yml

- #31 
- 한국투자증권 접근토큰 발급 및 Redis 내 저장
- 스케쥴링 적용(매일 7시)
- 한국투자증권 웹소켓 접속키 발급 및 Redis 내 저장
- 스케쥴링 적용(매년 1월 1일) / 애플리케이션 시작 시
- `RedisService` 내 조회 메서드 `get(String key)` 추가
- 코드 리뷰 후, 배포 서버 환경변수 수정하도록 하겠습니다.
- `@EnableScheduling` 어노테이션 설정 클래스 분리 필요

Feature: 한국투자증권 인증 API 연결

---

src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
src/main/java/muzusi/application/news/service/NewsManagementService.java
src/main/java/muzusi/domain/news/repository/NewsRepository.java
src/main/java/muzusi/domain/news/service/NewsService.java
src/main/java/muzusi/infrastructure/config/SchedulingConfig.java

- close #29 
- DB에 저장된 오래된 뉴스 삭제 스케쥴러 등록
- 날짜 기준 뉴스 검색 및 삭제 로직 구현
- 스케쥴러 등록 (매일 자정에 실시)
- 일단 이틀을 기준으로 이틀이 지난 뉴스를 삭제하고 있습니다. (전 날의 뉴스 또한 다음 날에 영향를 끼칠 수 있으니)
아니면, 생각하시는 일자에 대해서 말씀해주세요!
- JPA 네이밍 메서드 중 `deleteAllByIdInBatch`라는 메서드가 있습니다! 이것 이 제가 현재 (2a001073ff3974591e553af8774292cef2b5bed9)에서 작성한 `deleteByIds`과 똑같은 기능을 하지만, 익숙하지 않은 네이밍 메서드라 좀 더 이해하기 쉬울 수 있도록 JPQL을 직접 작성한 것입니다!
스케쥴러로 일정 시간이 지난 뉴스의 id값을 통해 한번에 삭제하는 쿼지를 날리는 스크린샷입니다.

Feature: 뉴스 삭제 스케쥴러 구현

---

src/main/java/muzusi/application/account/service/AccountManagementService.java
src/main/java/muzusi/application/account/service/UserAccountService.java
src/main/java/muzusi/application/auth/service/AuthService.java
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/domain/user/entity/User.java
src/main/java/muzusi/global/response/success/SuccessResponse.java
src/main/java/muzusi/presentation/account/api/AccountApi.java
src/main/java/muzusi/presentation/account/controller/AccountController.java

- #40 
- 계좌 생성 로직 구현
- 최초 계정 생성 시, 계좌 연결 및 계좌 생성횟수 1로 초기화
- `SuccessResponse`에서 `null`인 데이터 반환 처리
- 계좌 시드 부활에 대해 횟수를 제한할 것인지 의견을 묻고 싶습니다!
- `SuccessResponse.ok()`를 할 시, data가 null로 반환되는 문제를 처리했습니다.

Feature: 계좌 생성 로직 구현

---

build.gradle
src/main/java/muzusi/application/account/dto/AccountInfoDto.java
src/main/java/muzusi/application/account/service/UserAccountService.java
src/main/java/muzusi/domain/account/entity/Account.java
src/main/java/muzusi/domain/account/exception/AccountErrorType.java
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/presentation/account/api/AccountApi.java
src/main/java/muzusi/presentation/account/controller/AccountController.java

- close #40 
- 사용자의 전쳬 계좌 불러오기
- 사용자의 최신 계좌 (현재 계좌) 불러오기
- 최신 계좌를 불러오는 과정에서 `네이티브 쿼리`를 사용한 이유는 값을 찾으면 바로 해당 값만 불러오는 `LIMIT`를 사용하기 위해서 사용하였습니다.
- 전체 계좌 불러오기
- 최신 계좌 불러오기

Feature: 계좌 전체 불러오기 및 최신 계좌 불러오기

---

src/main/java/muzusi/application/stock/service/StockService.java
src/main/java/muzusi/application/trade/dto/TradeReqDto.java
src/main/java/muzusi/application/trade/service/StockTradeService.java
src/main/java/muzusi/domain/stock/exception/StockErrorType.java
src/main/java/muzusi/domain/stock/repository/StockRepository.java
src/main/java/muzusi/domain/trade/entity/Trade.java
src/main/java/muzusi/domain/trade/repository/TradeRepository.java
src/main/java/muzusi/domain/trade/service/TradeService.java
src/main/java/muzusi/domain/trade/type/TradeType.java
src/main/java/muzusi/presentation/trade/api/TradeApi.java
src/main/java/muzusi/presentation/trade/controller/TradeController.java

- #44 
- 주식 매수/매도 로직 구현
- 현재는 구매 예약이 없다는 상황을 가정하여 진행한 코드입니다. 추후에 예약을 구현하면 코드 로직상의 변화가 생깁니다!
- 주식 매수 성공
- 주식 매도 성공
- 디비 저장 상태

Feature: 주식 매수/매도 로직 구현

---

src/main/java/muzusi/application/account/service/AccountManagementService.java
src/main/java/muzusi/application/trade/dto/TradeReqDto.java
src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
src/main/java/muzusi/application/trade/service/StockTradeService.java
src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
src/main/java/muzusi/domain/account/entity/Account.java
src/main/java/muzusi/domain/trade/entity/TradeReservation.java
src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
src/main/java/muzusi/domain/trade/service/TradeReservationService.java
src/main/java/muzusi/infrastructure/config/MongoConfig.java

- close #44 
- 주식 거래 상태에 따른 분기 처리 (거래 성사 및 거래 예약)
- Trade Entity에 주문 시간 필드 추후에 추가하겠습니다.
- 매수된 내역을 관리하는 Entity가 필요할 것 같습니다.
- 카톡에서 얘기한 것 처럼, 예약 처리건은 차트표시를 위해 값을 불러오는 과정에서 처리하면 될 것 같습니다!
- 거래가 불가능하여 예약처리를 MongoDB에 넣은 사진

Feature: 주식 거래 분기에 따른 처리

---

src/main/java/muzusi/application/auth/dto/SignUpDto.java
src/main/java/muzusi/application/auth/helper/JwtHelper.java
src/main/java/muzusi/application/auth/service/AuthService.java
src/main/java/muzusi/global/security/jwt/JwtProvider.java
src/main/java/muzusi/presentation/auth/api/AuthApi.java
src/main/java/muzusi/presentation/auth/controller/AuthController.java

- UI상 닉네임을 보여주기 위한 Jwt Payload에 정보 추가
- Jwt Payload에 Nickname 정보 추가
- 회원가입시, token 재발급
- 회원가입 유효성검사 추가
- 최초 로그인 시, 닉네임은 서버에서 임의로 지정한 값이 디폴트로 들어가기 때문에 회원가입 시 token을 재발급해주었습니다.
- 프론트 측에서는 Access Token으로 닉네임을 추출하여 사용하면 될 것 같습니다. (추출 후 로컬 스토리지 등에 저장 후 사용?)
- 추가적으로, 정보 설정에서 닉네임을 업데이트 할 시, 위에서 말한 방식으로 닉네임을 업데이트 하면 될 것 같습니다. (로컬 스토리즈의 닉네임 값 업데이트)
- p.s. 닉네임 유효성 검사는 프론트 측 문구를 보고 똑같이 하였습니다.

Feature: Jwt Payload 정보 추가

---

src/main/java/muzusi/application/account/dto/AccountInfoDto.java
src/main/java/muzusi/application/trade/dto/TradeReqDto.java
src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
src/main/java/muzusi/application/trade/service/StockTradeService.java
src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
src/main/java/muzusi/domain/account/entity/Account.java
src/main/java/muzusi/domain/account/exception/AccountErrorType.java
src/main/java/muzusi/domain/holding/entity/Holding.java
src/main/java/muzusi/domain/holding/exception/HoldingErrorType.java
src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
src/main/java/muzusi/domain/holding/service/HoldingService.java
src/main/java/muzusi/domain/stock/entity/Stock.java
src/main/java/muzusi/presentation/trade/api/TradeApi.java
src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
src/test/java/muzusi/application/trade/service/StockTradeServiceTest.java
src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java

- close #54 
- 매수/매도 로직 처리
- Holding Entity 구현
- 매수, 매도 과정 중 예외처리
- 관련 test 코드 작성
- `StockTradeExecutor.handleStockPurchase`에서 `Holding`을 가져올 때 `get()`을 통해 Optional을 가져오는 이유는 조건문을 통해 해당 주식이 존재하는지 확인했기 떄문입니다!
- 예약 주식 취소로직은 아직 구현되지 않았습니다!
- `StockTradeExecutor`, `StockTradeService`, `TradeReservationHandler`로직 상에서 같은 Account, Holding 여러번 호출하니 쿼리가 여러번 쿼리가 날아가는 문제가 있었습니다. '같은 트랜잭션이면 1차 캐시에 있기에 문제가 없는 것이 아닌가?'라는 생각을 가지고 인터넷을 찾아보니 다음의 [블로그](https://kimsy8979.tistory.com/41)를 보게 되었습니다. (참고가 될 수 있으니 가져와봤습니다!)
간단히 요약하면, pk값을 통한 조회는 1차 캐시에 저장이 되지만, 다른 네이밍 메서드는 JPQL로 동작하기에 1차 캐시에 올라가지 않아 계속해서 db에 접근하는 것이었습니다.
그래서, 강제로 1차캐시에 넣고 조회하는 로직 등 다양한 로직을 시도했지만, 저희의 코드는 결국에 pk를 이용하는 것이 아니기떄문에 문제를 해결하지 못했습니다.
이 부분에 대해서 인지해주셨으면 좋겠고, 좋은 방법 있다면 말씀해주세요! (매개변수로 조회한 값을 넘길 시, 사용하지 않는 값도 넘겨야 하는 문제)

Feature: 매수된 주식 관리 및 매수/매도 로직 처리

---

src/main/java/muzusi/application/kis/service/KisRankingService.java
src/main/java/muzusi/application/stock/service/StockRankingService.java
src/main/java/muzusi/domain/stock/type/StockRankingType.java
src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
src/main/java/muzusi/presentation/stock/api/StockRankingApi.java
src/main/java/muzusi/presentation/stock/controller/StockRankingController.java

- #56 
- 주식 순위 조회 API 추가 - `GET/stocks/rank?type=`
- 한국투자증권 주식 순위 API 호출 후 저장 시 Redis 내 기존 데이터 미삭제 오류 발견 → 주식 순위 저장 전 삭제 메서드 추가하였습니다.
-  EC2 Redis 내 누적 데이터는 모두 삭제 처리 하였습니다.
미래에셋비전스펙1호 값 오류는 일시적 오류 같습니다.
- Swagger 문서 작성 시 동일 응답 코드의 Example Object는 처음 요소만 나타나므로 현재는 3개(급상승/급하락/거래량) 순위 API 응답값을 하나로 합쳐서 표기해놓았습니다. 
동일 응답 코드의 여러 Exmaple Object 사용 시 커스텀 어노테이션 및 추가 Swagger 설정이 필요하다고 합니다. 해당 부분을 진행하기로 한다면 적용시키겠습니다!

Feature: 주식 순위 조회 API

---

src/main/java/muzusi/application/account/service/UserAccountService.java
src/main/java/muzusi/domain/account/exception/AccountErrorType.java
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/presentation/account/api/AccountApi.java

- 무분별한 계좌 개설로 인해 처리량의 복잡도가 발생. 하루에 1회 계좌 개설 가능
- 가장 최신 계좌 기준으로 날짜 확인 후 계좌 개설
- 현재는 하루에 1회로 제한하였지만, 계좌 개설 횟수 제한 날짜에 대해 다른 의견있다면 제시해주세요!
- `UserAccountService.connectNewAccount()`에서 최신 계좌의 날짜를 가져와 조건문을 통해 확인 하는 과정에서 `latestCreatedAt != null`가 있습니다. 서버의 로직상 최초 가입을 하면 계좌를 연동해주어 `null`체크를 안해줘도 되지만, 예외 상황이 발생할 수 있기에 추가하였습니다.

Feature: 무분별한 계좌 개설 제한

---

src/main/java/muzusi/application/news/dto/NewsInfoDto.java
src/main/java/muzusi/application/news/service/NewsManagementService.java
src/main/java/muzusi/domain/news/repository/NewsRepository.java
src/main/java/muzusi/domain/news/service/NewsService.java
src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java

- News 중복성 Link를 통한 중복성 확인을 통해 안전성 높이고, 홈화면에서 보이는 뉴스는 로그인되기 전 상태도 보이니 엔드포인트 허용해야되는 상황
- News link 중복성 체크로 수정
- 엔드포인트 허용
x

Refact: News 로직 수정 및 Security Endpoint 허용

---

src/main/java/muzusi/infrastructure/kis/KisRankingClient.java

- 주말 및 공휴일 간 등락률 순위 저장 시 이상하게 저장되는 경우 존재하여 이에 대한 수정 소요 발생
- 거래량 순위 조회 시 종목 변경 요청: 우선주 → 전체
- 등락률 순위 조회 시 조회 일수 변경 
- 기존 `1일` → 변경 `전체`
- 거래량 순위 조회 종목 변경
- 기존 `우선주` → 변경 `전체`

Fix: 공휴일 간 주식 순위 저장 시 오류로 인한 변경

---

src/main/java/muzusi/application/stock/dto/StockChartInfoDto.java
src/main/java/muzusi/application/stock/service/StockHistoryService.java
src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
src/main/java/muzusi/domain/stock/entity/StockDaily.java
src/main/java/muzusi/domain/stock/entity/StockMonthly.java
src/main/java/muzusi/domain/stock/entity/StockWeekly.java
src/main/java/muzusi/domain/stock/entity/StockYearly.java
src/main/java/muzusi/domain/stock/repository/StockDailyRepository.java
src/main/java/muzusi/domain/stock/repository/StockMonthlyRepository.java
src/main/java/muzusi/domain/stock/repository/StockWeeklyRepository.java
src/main/java/muzusi/domain/stock/repository/StockYearlyRepository.java
src/main/java/muzusi/domain/stock/service/StockDailyService.java
src/main/java/muzusi/domain/stock/service/StockMonthlyService.java
src/main/java/muzusi/domain/stock/service/StockService.java
src/main/java/muzusi/domain/stock/service/StockWeeklyService.java
src/main/java/muzusi/domain/stock/service/StockYearlyService.java
src/main/java/muzusi/domain/stock/type/StockPeriodType.java
src/main/java/muzusi/infrastructure/config/security/SecurityConfig.java
src/main/java/muzusi/presentation/stock/api/StockHistoryApi.java
src/main/java/muzusi/presentation/stock/controller/StockHistoryController.java
src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java

- 일/월/주/년 별 주식 차트 데이터 조회의 필요성
- 각 기간별 몽고디비 컬렉션 생성
- 조회 로직 생성
x
데이터가 많다보니 조회 중 성능 개선을 위해 몽고 DB에 index를 추가하였습니다.
1. 인덱스 적용 전 (112ms)
2. 인덱스 적용 후 (25ms)

Feature: 주식 차트 기간별 조회 구현

---

src/main/java/muzusi/application/kis/dto/KisDto.java
src/main/java/muzusi/application/kis/service/KisRankingService.java
src/main/java/muzusi/application/stock/service/StockRankingService.java
src/main/java/muzusi/global/redis/RedisService.java
src/main/java/muzusi/infrastructure/kis/KisConstant.java
src/main/java/muzusi/presentation/stock/api/StockRankingApi.java

- #64 
- 한국투자증권 주식 순위 조회 시간 저장 로직 추가하였습니다.
- `LocalDateTIme`저장 시 직렬화 및 형식 지정을 위한 어노테이션, DTO 클래스 추가
```
{
"code": 200,
"message": "요청이 성공하였습니다.",
"data": {
"rank": [
{
"name": "데이원컴퍼니",
"code": "373160",
"rank": 1,
"price": 7800,
"prdyVrss": -5200,
"prdyCtrt": -40.0,
"avrgVol": 5373704
},
...
{
"name": "한국첨단소재",
"code": "062970",
"rank": 30,
"price": 6400,
"prdyVrss": -460,
"prdyCtrt": -6.71,
"avrgVol": 6561625
}
],
"time": "2025-01-27 03:08:00"
}
}
```
postman 결과를 캡쳐하기에는 내용이 길어 텍스트로 대체합니다. 
결과는 동일합니다.
- 저번에 이야기한 것 처럼 Redis 트랜잭션은 적용하지 않았습니다. 
그러나, #51 에서 적용한 예외 처리에 의해 나머지 주식 순위 조회 및 저장 메서드들이 진행되지 않아 에러 발생 이후 메서드는 실행되지 않는 것 같습니다.

Feature: 주식 순위 갱신 시간 저장

---

src/main/java/muzusi/application/account/dto/AccountInfoDto.java
src/main/java/muzusi/application/account/dto/TradeInfoDto.java
src/main/java/muzusi/application/account/service/TradeHistoryService.java
src/main/java/muzusi/application/trade/dto/TradeReqDto.java
src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
src/main/java/muzusi/domain/account/exception/AccountErrorType.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/domain/trade/entity/Trade.java
src/main/java/muzusi/domain/trade/entity/TradeReservation.java
src/main/java/muzusi/domain/trade/repository/TradeRepository.java
src/main/java/muzusi/domain/trade/service/TradeService.java
src/main/java/muzusi/presentation/account/api/AccountApi.java
src/main/java/muzusi/presentation/account/controller/AccountController.java
src/test/java/muzusi/application/trade/service/StockTradeExecutorTest.java
src/test/java/muzusi/application/trade/service/StockTradeServiceTest.java
src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java

1. 계좌의 거래내역을 알 필요가 있음.
2. Trade에 StockName을 넣어 주식 종목에 대해 반환해주어야 함. 그래서 말했던 것처럼, 매핑보다는 필드명 자체를 넣는게 좋다고 판단
- 계좌 내역 정보 반환 시, 예약 거래에 대한 금액도 같이 반환 `reversedPrice`
- 계좌 거래내역 반환 추가
- Trade 필드 변경
x

Feature: 계좌 거래내역 조회 및 Trade 필드 수정

---

src/main/java/muzusi/application/stock/dto/StockItemDto.java
src/main/java/muzusi/application/stock/service/StockHistoryService.java
src/main/java/muzusi/application/stock/service/StockSearchService.java
src/main/java/muzusi/domain/stock/entity/StockItem.java
src/main/java/muzusi/domain/stock/repository/StockItemCustomRepository.java
src/main/java/muzusi/domain/stock/repository/StockItemCustomRepositoryImpl.java
src/main/java/muzusi/domain/stock/repository/StockItemRepository.java
src/main/java/muzusi/domain/stock/service/StockItemService.java
src/main/java/muzusi/presentation/stock/api/StockApi.java
src/main/java/muzusi/presentation/stock/controller/StockController.java

- 검색창에서 주식에 대한 자동 완성과 종목코드를 매핑해서 보내줘야 함.
- 검색어를 통한 주식 검색 및 코드 매핑
- 주식 조회수를 기준으로 정렬 구현 (조회수 기준 내림차순 -> 이름 기준 오름차순)
- DB, Redis, 서버 내 메모리 등 다양한 시도를 해봤는데, 영구적인 저장과 속도를 고려했을 때, MongoDB를 이용하는 것이 적절하여 적용했습니다!
다른 의견 있다면 말씀해주세요!
- 프론트에서는 검색마다 호출하는 것이 아닌 디바운싱을 사용하여 호출하면 부하가 적을 것 같습니다!
- 종목에 들어가면 (특정 종목에 들어가 웹소켓 연결하면) stockCode를 통해서 `StockItemService`에 searchCount 업데이트하면 될 것 같습니다! (조회수로 검색어를 정렬하기 위함)
1. 조회수 모두 동일 (이름순 정렬)
2. 조회수 우선 정렬

Feature: 주식 검색어 자동완성 구현

---

src/main/java/muzusi/application/trade/scheduler/TradeScheduler.java
src/main/java/muzusi/application/trade/service/StockTradeExecutor.java
src/main/java/muzusi/application/trade/service/TradeReservationCleaner.java
src/main/java/muzusi/domain/holding/entity/Holding.java
src/main/java/muzusi/domain/trade/service/TradeReservationService.java
src/test/java/muzusi/application/trade/service/TradeReservationCleanerTest.java

- #60 
- 예약 매수/매도 내역 삭제 처리
- 장마감 시간 예약 내역 삭제 스케쥴러 적용
- 삭제 로직 중, 같은 Account, Holding에 대해서 여러번 쿼리 호출을 막기 위해 userId 및 매수/매도 내역을 분리하여 처리하였습니다

Feature: 장 마감 시, 예약 내역 삭제 로직 구현

---

src/main/java/muzusi/infrastructure/config/SchedulingConfig.java

- #72 
- `SchedulingConfig` 내 쓰레드풀 설정 코드 추가
스케줄링 시 기본적으로 `SimpleAsyncTaskScheduler`를 적용하여 단일 쓰레드로 동작한다는 것을 알게되었습니다.
스케줄링 쓰레드풀 적용 방법 관련하여 
[스프링 공식문서](https://docs.spring.io/spring-framework/reference/integration/scheduling.html#scheduling-task-scheduler)에서는 `TaskScheduler`를 커스터마이징한 Bean을 등록할 수 있다고 되어있습니다.
[스프링부트 공식문서](https://docs.spring.io/spring-boot/reference/features/task-execution-and-scheduling.html)에서는yaml 파일에서  name space를 통해 자동 설정 가능하도록 지원한다고 되었습니다. 
> 스프링부트 패키지 내 설정 파일: `TaskSchedulingProperties`
두 방법 중 `TaskScheduler`를 커스텀하여 Bean으로 등록하는 방법을 선택한 이유는 아래와 같습니다.
- 코드 내에 쓰레드풀 설정에 대한 명시적 표현
- 쓰레드풀 사이즈 설정 관련하여 추가 코드(`Runtime.getRuntime().availableProcessors()` 등)를 통해 유연한 대응 가능
---
그리고, 몇몇 블로그들에서 `TaskScheduler` 빈 등록 후, 스케줄링 작업 메서드에 `@Async("taskScheduler")` 어노테이션을 사용하여 적용하는 경우를 보았습니다. …

Feature: 스케줄링 전용 쓰레드풀 설정

---

src/main/java/muzusi/application/trade/service/TradeReservationTrigger.java
src/main/java/muzusi/domain/holding/entity/Holding.java
src/main/java/muzusi/domain/holding/service/HoldingService.java
src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
src/main/java/muzusi/domain/trade/service/TradeReservationService.java
src/test/java/muzusi/application/trade/service/TradeReservationTriggerTest.java

- close #60 
- 예약 분기별 성공 로직 구현
- 관련 테스트 코드 작성
- 짜면서 아쉬웠던 점은 이전에 `StockTradeExecutor`와 합쳐 로직을 진행하고자 하였으나, 예외값 확인하는 로직 및 몇몇개의 로직에서 차이점이 있어 사용하지 못했습니다. 그래서, 코드가 복잡해 보일 수 있다고 생각하는데 확인해주시길 바랍니다!
- 서버 내에서 실행되는 로직이고, 처리 속도를 높이기 위해 비동기를 사용했습니다. 이 로직에서 비동기가 적절할까? 라는 생각이 드는데 어떻게 생각하시나요? (만약 예약된 주식의 종류가 많아진다면, 쓰레드풀을 설정해야할 듯)

Feature: 주식 예약 내역 성공 처리 로직 구현

---

src/main/java/muzusi/application/trade/dto/ReservationInfoDto.java
src/main/java/muzusi/application/trade/service/UserTradeReservationService.java
src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
src/main/java/muzusi/domain/trade/service/TradeReservationService.java
src/main/java/muzusi/presentation/trade/api/TradeReservationApi.java
src/main/java/muzusi/presentation/trade/controller/TradeReservationController.java

사용자가 예약한 내역을 조회가 필요 - 확인 및 취소를 위함
- 예약 주식 정보 반환
얘기를 나눈 것처럼 전체 내역 조회만 구현하였습니다. 후에 필요시, 종목에 대한 예약 내역 추가하겠습니다

Feature: 예약한 주식 정보 반환 기능 추가

---

src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
src/main/java/muzusi/application/kis/service/KisStockService.java
src/main/java/muzusi/domain/stock/entity/StockMinutes.java
src/main/java/muzusi/domain/stock/repository/StockMinutesRepository.java
src/main/java/muzusi/domain/stock/service/StockMinutesService.java

- #80 
- 9시 10분~15시 30분동안 10분마다 한국투자증권 주식 분봉 데이터 호출 및 Redis 내 저장
- 16시에 Redis → MongoDB 데이터 이관 및 삭제
해당 부분은 값 저장 시에만 영국시간에 맞춰서 저장된다고 합니다. 값을 꺼내서 사용할 때는 다시 한국 시간만큼 시차가 더해져서 출력되기 때문에 문제가 없는 것 같습니다.
주식 분봉 데이터는 10분 단위로 저장을 합니다.
9:10분에 한국투자증권 API를 호출하여 9:00~10분 데이터를 저장합니다. 
모든 주식 정보에 대해서 API를 호출하기 때문에 저장하는데 5분 내외의 시간이 소요됩니다.
따라서 9:00~9:10분의 분봉은 9:15분 이후에 조회가 가능할 것 같습니다.
(@gugitgugit ) 해당 부분을 고려하였을 때 가장 최근 분봉은 프론트에서 웹 소켓을 통하여 보여주는 방식을 선택해야 할 것 같습니다.
다른 의견이 있다면 다같이 이야기 나눠보면 좋을 것 같습니다!
현재 `KisStockService`에 주식 분봉 데이터 저장 메서드들을 구현한 상태입니다.
해당 부분 관련해서 클래스명이 이것이 맞을까, 구조는 이게 맞을까라는  의문이 들기도 하였습니다.
다른 적절한 의견이 있으시다면 코멘트 부탁드리겠습니다!
또한, [`KisScheduler.runSaveDailyStockMinutesChartJob()`](https://github.com/Team-Digimon/muzusi-was/blob/a51f3bdefdf367e98602f8d561236ef2ae12e842/src/main/java/muzusi/application/ki …

Feature: 주식 분봉 데이터 저장

---

src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
src/main/java/muzusi/application/stock/dto/StockPriceDto.java
src/main/java/muzusi/infrastructure/config/RedisConfig.java
src/main/java/muzusi/infrastructure/redis/RedisService.java
src/main/java/muzusi/infrastructure/redis/constant/KisConstant.java

- #82 
- 주식 분봉데이터 종가(close) 기준 현재가 저장
- Redis Hash 사용으로 인한 Hash Serializer/Deserializer 설정 추가
hash내 현재가 값이 최근 분봉 데이터 종가 값과 동일합니다.
> 위 사진에서 분봉 데이터 1,2는 중복된 값이라 해당 부분은 무시해주셔도 될 것 같습니다.

Feature: 주식 현재가 저장

---

src/main/java/muzusi/application/trade/scheduler/TradeScheduler.java
src/main/java/muzusi/application/trade/service/TradeReservationProcessor.java
src/main/java/muzusi/application/trade/service/TradeReservationTrigger.java
src/main/java/muzusi/infrastructure/redis/RedisService.java
src/test/java/muzusi/application/trade/service/TradeReservationProcessorTest.java
src/test/java/muzusi/application/trade/service/TradeReservationTriggerTest.java

- 주식 예약 내역에 대한 주기적인 확인을 통해 처리를 해야함.
- 10분 단위로 주식 현재가를 불러와 처리하기에, 예약 내역은 5분부터 시작해 10분단위로 진행.
- 10분 단위로 불러오는 주식 현재가의 저가, 고가를 이용하여 예약 내역 범위 확인.
- 스케줄링 적용하여 예약 내역 확인 처리
- 관련 테스트 코드 작성
- 현재는 9시는 15분부터, 15시는 5~25분 까지, 나머지는 5~55분에 처리하고 있습니다. 다른 시간에 대한 의견이 있으면 말씀해주세요!

Feature: 예약 내역 확인 처리 스케줄링 적용

---

src/main/java/muzusi/application/kis/service/KisStockMinutesService.java

- 한국투자증권 주식 분봉 데이터 호출 시 테스트 용도 설정 시간 미변경으로 오류 발생
- 현재 시간으로 변경
- 서버 내 주식 분봉데이터 삭제 후 제가 직접 호출해서 하루 치 넣도록 하겠습니다.

Fix: 한국투자증권 주식 분봉 데이터 API 호출 시간 오류 수정

---

src/main/java/muzusi/application/account/dto/AccountDetailsDto.java
src/main/java/muzusi/application/account/dto/AccountProfitInfoDto.java
src/main/java/muzusi/application/account/scheduler/AccountScheduler.java
src/main/java/muzusi/application/account/service/AccountProfitUpdateExecutor.java
src/main/java/muzusi/application/account/service/UserAccountService.java
src/main/java/muzusi/application/holding/service/UserHoldingService.java
src/main/java/muzusi/domain/account/entity/AccountProfit.java
src/main/java/muzusi/domain/account/repository/AccountProfitRepository.java
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/service/AccountProfitService.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
src/main/java/muzusi/domain/holding/service/HoldingService.java

- 일별 수익 그래프를 위한 일별 수익률 저장 및 반환 필요
- 일별 수익률 저장
- 일별 수익률 반환  (14일)
- 14일 이후 삭제 내용은 다음 pr에서 진행하겠습니다
- 일별 수익률 저장 메서드에서 `saveAll()`을 선택하였습니다
1. Id가 `IDENTITY`형식인데 둘 다 쿼리 하나하나 날리지 않나? -> `saveAll()`은 하나의 트랜잭션을 관리하기 때문에 속도가 더 빠름
2. 배치 인서트 하면 안되나? -> id 저장 방법 변환 or jdbctemplate 사용. but, 100명의 사용자도 없는 이 상황에서는 고려사항이 아니라고 판단.
라는 저의 생각으로 `saveAll()`을 적용시켰습니다
- 내용은 그냥 임의로 넣은 것이기 때문에 중복된 데이터로 있습니다

Feature: 계좌 일별 수익률 추가 및 반환

---

src/main/java/muzusi/infrastructure/kis/KisRankingClient.java
src/main/java/muzusi/infrastructure/kis/KisRequestFactory.java
src/main/java/muzusi/infrastructure/kis/KisStockClient.java

- 한국투자증권 REST API 호출 클래스 `Kis___Client` 내 헤더 생성 코드 중복으로 인한 클래스 분리
- 헤더 내 포함 필드 통합
- trId를 통한 헤더 생성 메서드 분리
- HttpHeaders 객체 생성을 담당하는 클래스를 별도로 둔 심플 팩토리 패턴이라 생각하여 클래스명으로 Factory를 사용하였으나, 클래스명에 관한 고민이 여전히 남은 상태이긴 합니다.

Refact: 한국투자증권 REST API 요청 헤더 생성 팩토리 클래스 분리

---

src/main/java/muzusi/application/account/scheduler/AccountScheduler.java
src/main/java/muzusi/application/account/service/AccountProfitManager.java
src/main/java/muzusi/domain/account/repository/AccountProfitRepository.java
src/main/java/muzusi/domain/account/service/AccountProfitService.java
src/main/java/muzusi/presentation/account/api/AccountApi.java

- 계좌 일일 수익률은 14일까지만 필요. 그 이후의 데이터 삭제가 필요.
- 삭제 로직 구현
- 계좌 swagger 작성
- 현재 작은 데이터라 단순히 호출하여 삭제하는 과정을 거치고 있습니다.
news 부분에서도 이와 비슷한 로직이 있는데, 추후에 더 좋은 방법 (DB 파티셔닝 등)을 공부하여 적용시켜 보겠습니다.

Feature: 오래된 계좌 수익률 삭제 로직 구현

---

src/main/java/muzusi/application/news/scheduler/NewsScheduler.java
src/main/java/muzusi/application/news/service/NewsManagementService.java
src/main/java/muzusi/domain/news/repository/NewsRepository.java
src/main/java/muzusi/domain/news/service/NewsService.java

- 전의 로직에서는 날짜가 지난 데이터를 불러와 그 데이터들의 pk값을 이용하여 삭제하는 불필요한 과정이 있었음.
시간을 기준으로 바로 삭제하는 로직 작성
- 뉴스 삭제 로직 수정
- 뉴스 삭제 기간 수정 (1일 <- 50개의 데이터만 보여주기에 1일 이상의 데이터가 필요없음)
- 뉴스 삭제 스케쥴러 수정 (자정에 삭제하면 전날의 뉴스가 다 사라짐. 뉴스를 받아오는 시간 전까지 데이터가 없을 수 있기에, 자정 5분 전으로 수정)
이번 pr과 같이 DB 파티셔닝에 대해 공부해보도록 하겠습니다.

Refact: 뉴스 삭제 로직 수정

---

src/main/java/muzusi/presentation/websocket/inteceptor/StompInterceptor.java

- StompJS 7.0.0 이상 라이브러리 내 `disconnect` 삭제 및 `deactivate` 변경
- `deactivate` 내 header 포함 불가
- 구독 해제 확인 메서드 DISCONNECT → UNSUBSCRIBE 변경

Feature: StompJS disconnect 메서드 deprecated에 따른 코드 변경

---

.gitignore
build.gradle
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/repository/CustomAccountRepository.java
src/main/java/muzusi/domain/account/repository/CustomAccountRepositoryImpl.java
src/main/java/muzusi/domain/holding/repository/CustomHoldingRepository.java
src/main/java/muzusi/domain/holding/repository/CustomHoldingRepositoryImpl.java
src/main/java/muzusi/domain/holding/repository/HoldingRepository.java
src/main/java/muzusi/domain/holding/service/HoldingService.java
src/main/java/muzusi/infrastructure/config/QueryDslConfig.java

- 가독성 + 컴파일 시점에서의 오류 문구를 찾기 위한 QueryDsl 적용
- QueryDsl 의존성 구현 및 gitignore을 통한 git 추척 제거
- Account, Holding 등의 복잡한 JPQL 문구 QueryDsl 적용
1. **벌크 연산 중 영속성 컨텍스트 문제**
- 쿼리DSL을 통한 벌크 연산을 사용할 시, DB에 바로 접근을 하는 것이기에 영속성 컨텍스트의 값을 삭제시키지 않음.
- Holding 삭제 과정 중, 벌크 삭제로 인해 영속성 컨텍스트에서 바로 삭제 되지 않기에 같은 트랜잭션에서 조회 시, 그대로 조회 가능. (만약, 이것이 벌크 수정 연산이라면 업데이트 되기 전의 값을 조회한다는 뜻.)
- EntiyManager을 통해 직접 flush() 및 close()를 해줘야 함.
- 하지만, 해당 로직에서 account의 정보를 업데이트 하는 과정이 있기에 flush(), close()를 하게되면, account의 더티체킹을 하지 못하기에 적용하지는 않음
2. **QueryDsl 서브쿼리에서의 limit 연산 적용 불가능**
- QueryDsl 서브쿼리, JPQL은 limit가 적용되지 않는다고 함. 그래서, 최신 계좌는 id가 가장 큰 값이니, 그것을 이용하여 작성 (created를 기준으로하면 3중 쿼리가 되기에 id를 이용함) 
- 참고 블로그 [QueryDSL에서 SubQuery 에는 limit 를 사용 할 수 없다.](https://j-k4keye.tistory.com/75), [How to use limit() and offset() in subquery? - git …

Refact: JPQL 문구 QueryDsl 적용

---

src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java

- 한국투자증권 웹소켓 연결 시 이미 구독된 종목에 대한 불필요 연결 확인
- 이미 구독된 종목의 경우 연결 미실행
- 이미 구독하고 있는 종목이 아닐 경우에만 에러 발생

Fix: 한국투자증권 웹소켓 연결 로직 수정

---

src/main/java/muzusi/application/websocket/scheduler/WebSocketConnectionScheduler.java
src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
src/main/java/muzusi/infrastructure/kis/KisWebSocketHandler.java

- 한국투자증권 웹소켓 세션 종료 시각(15:30)에 에러 발생
- 15:30에 동시에 세션 종료 + 하트비트 핑 송신으로 인한 에러 발생
- 하트비트 핑 송신 시간 수정 ~15:30 → ~15:29
- 세션 연결 종료 전 구독 종목 해제

Fix: 한국투자증권 웹소켓 세션 연결 종료 에러 수정

---

src/main/java/muzusi/application/kis/scheduler/KisScheduler.java
src/main/java/muzusi/application/kis/service/KisOAuthService.java
src/main/java/muzusi/infrastructure/kis/KisAuthService.java
src/main/java/muzusi/infrastructure/kis/KisRealTimeTradeHandler.java
src/main/java/muzusi/infrastructure/kis/KisRequestFactory.java
src/main/java/muzusi/infrastructure/kis/KisWebSocketHandler.java

- 클래스 책임에 따른 웹소켓 연결 관리 메서드 분리
- `afterConnectionEstabilished()`, `afterConnectionClosed()` 및 `WebSocketSession session` 위치 변경
- 조금 더 유연한 구조와 추가 계좌를 통한 세션 확대를 생각하면 웹소켓 관리 별도의 클래스 생성이 맞는 것 같습니다. 변경 시 연결 과정 등과 처리 방식에 대해 조금 더 고민할 필요가 있어 해당 부분의 차후 필요에 따라 수정하도록 하겠습니다.

Refact: 웹소켓 연결 관리 메서드 위치 변경

---

src/main/java/muzusi/application/trade/dto/ReservationInfoDto.java
src/main/java/muzusi/application/trade/service/StockTradeService.java
src/main/java/muzusi/application/trade/service/TradeReservationHandler.java
src/main/java/muzusi/application/trade/service/TradeReservationProcessor.java
src/main/java/muzusi/domain/trade/entity/TradeReservation.java
src/main/java/muzusi/domain/trade/repository/TradeReservationRepository.java
src/main/java/muzusi/domain/trade/service/TradeReservationService.java
src/main/java/muzusi/presentation/trade/api/TradeApi.java
src/main/java/muzusi/presentation/trade/controller/TradeController.java
src/test/java/muzusi/application/trade/service/TradeReservationHandlerTest.java

- 얘약 내역은 정형화된 데이터임. 또한, 일관성이 중요함. nosql보다는 rdb가 적절하다고 판단.
- rdb 변경
x

Refact: 예약 내역 데이터 관리 RDB로 변경

---

src/main/java/muzusi/application/account/dto/AccountInfoDto.java
src/main/java/muzusi/application/account/service/UserAccountService.java
src/main/java/muzusi/domain/account/entity/Account.java
src/main/java/muzusi/domain/account/repository/AccountRepository.java
src/main/java/muzusi/domain/account/repository/CustomAccountRepository.java
src/main/java/muzusi/domain/account/repository/CustomAccountRepositoryImpl.java
src/main/java/muzusi/domain/account/service/AccountService.java
src/main/java/muzusi/presentation/account/api/AccountApi.java

이전 계좌 조회 시, 주식 수익률 반환 필요
- 계좌 재발급 시, 이전 계좌 수익률 갱신
- 전체 계좌 조회 시, 최신 게좌 제외
x

Feature: 이전 계좌 조회 시, 주식 수익률 반환

---

.github/workflows/cd.yml
.github/workflows/ci.yml

default branch 변경으로 인한 CI/CD 브랜치명 변경
- 브렌치명 변경
x

Refact: default branch 변경으로 인한 CI/CD 브랜치명 변경

---

src/main/java/muzusi/application/kis/service/KisStockMinutesService.java
src/main/java/muzusi/domain/stock/repository/StockMinutesCacheRepository.java
src/main/java/muzusi/domain/stock/repository/StockPriceCacheRepository.java
src/main/java/muzusi/domain/stock/service/StockMinutesService.java
src/main/java/muzusi/domain/stock/service/StockPriceService.java

- #107 작업 전 `KisStockMinutesService` 클래스 내 책임 분리 필요
: `KisStockMinutesService` 내에서 `RedisService`를 직접 호출 X → 주식 분봉 데이터 & 주식 현재가 저장 용 클래스 분리
- `StockMinutesCacheRepository` 추가 및 `StockMinutesService` 내 주식 분봉 데이터 캐싱 관련 메서드 추가
- `StockPriceCacheRepository` 및 `StockPriceService` 추가
- 현재 존재하는 주식 현재가 조회 로직들(`TradeReservationTrigger.triggerTradeReservations()`)에도 차후 `StockPriceService`를 적용해야할 것 같습니다.
현재는 PR에 대한 승인이 이루어지지 않아 기타 다른 코드들은 수정하지 않았습니다!

Refact: 주식 분봉 차트 및 현재가 캐싱 클래스 분리

---

src/main/java/muzusi/application/kis/service/KisStockChartUpdater.java
src/main/java/muzusi/application/kis/service/KisStockRankingUpdater.java
src/main/java/muzusi/infrastructure/config/GuavaConfig.java
src/main/java/muzusi/infrastructure/config/RedisConfig.java
src/main/resources/application.yml

- 한국투자증권 REST API 호출 유량 제한 정책 대응을 위한 Guava 라이브러리의 `RateLimiter` 전역 적용
- 초당 20건
- 한국투자증권 API 호출 관련 `RateLimiter` 빈 등록 | (68919a66a2c512ef6b24f4e9c99c16c4774b2bcc)
- 호출 유량 제한량과 일치하는 `20`으로 설정 시 호출 유량 제한 에러 응답이 오는 경우가 있었습니다. 이는 한국투자증권이 슬라이딩 윈도우 방식으로 쓰로틀링을 적용하고 있는 것으로 추측되며, 그로 인하여 API 호출이 일시적으로 몰리는 경우에 여전히 호출 응답 오류 발생이 가능한 것으로 추측됩니다. 
- 따라서, 보수적으로 처리율 제한량을 `15`로 설정하였습니다.
- 한국투자증권 API 호출 로직 내 RateLimiter 빈 적용 | (5708d8917a9626009690690d4bcd6b5a502cd338)
- 환경변수 내 `REDIS_PASSWORD` 존재 시 패스워드 설정 로직 추가 | (4850582b7e5fbc8b1e1f901862fbdbd9b4eb51b6)
&nbsp; 현재 한국투자증권 API를 받아오는 작업은 다음과 같습니다.
- 한국투자증권 앱키/웹소켓접속키 발급
- 주식 현재가
- 주식 순위
&nbsp; 앱키/웹소켓 접속키 발급의 경우에는 애플리케이션 시작 시 & 주식 시장 시작 전 수행되기 때문에 호출 유량 제한이 일어날 가능성이 없기 때문에 쓰로틀링 적용하지 않았습니다.
&nbsp; 주식 순위와 주식 현재가 API 호출 작업은 주식 시장이 열리는 시간에 10분 단위로 해당 작업들이 겹쳐서 …

Feature: 한국투자증권 API 호출 로직 내 RateLimiter 전역 적용
